services:
  app:
    container_name: gardenia-app-container
    image: ${IMAGE_NAME}
    build: .
    ports:
      - "8501:8501"
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_NAME=${DB_NAME}

  db:
    image: ankane/pgvector
    container_name: gardenia-db-container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - gardenia_data:/var/lib/postgresql/data

volumes:
  gardenia_data: