services:
  db:
    image: ankane/pgvector
    container_name: gardenia-db-container
    networks:
      - gardenia-net
    environment:
      - POSTGRES_USER=gardenia
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=gardenia
    ports:
      - 5432:5432
    volumes:
      - gardenia_data:/var/lib/postgresql/data

volumes:
  gardenia_data:

networks:
  gardenia-net:
    external: true